ARG NODE_VERSION=20
ARG CLIENT_PORT=3000
ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL
ARG TEAM_NAME

FROM node:$NODE_VERSION-bookworm AS base

WORKDIR /app

FROM base AS builder

ARG CLIENT_PORT
ARG EXTERNAL_SERVER_URL
ARG INTERNAL_SERVER_URL
ARG TEAM_NAME

ENV EXTERNAL_SERVER_URL=$EXTERNAL_SERVER_URL \
  INTERNAL_SERVER_URL=$INTERNAL_SERVER_URL \
  TEAM_NAME=$TEAM_NAME

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/shared/dist/ /app/packages/client/dist/ && yarn build:client

FROM node:$NODE_VERSION-bookworm-slim AS production

ARG CLIENT_PORT

WORKDIR /app

COPY --from=builder /app/package.json /app/yarn.lock /app/lerna.json ./
COPY --from=builder /app/packages/client/package.json /app/packages/client/package.json
COPY --from=builder /app/packages/shared/package.json /app/packages/shared/package.json
RUN yarn install --production=true --frozen-lockfile --ignore-scripts

ENV NODE_ENV=production \
  CLIENT_PORT=$CLIENT_PORT

COPY --from=builder /app/packages/client/dist/ /app/packages/client/dist/
COPY --from=builder /app/packages/client/server/ /app/packages/client/server/
COPY --from=builder /app/packages/shared/dist/ /app/packages/shared/dist/

EXPOSE $CLIENT_PORT

USER node

CMD [ "node", "/app/packages/client/server/index.js" ]
