version: '3.9'

services:
  client:
    container_name: prakticum-client
    image: prakticum-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    env_file:
      - .env
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    depends_on:
      - server
    networks:
      - game
  server:
    container_name: prakticum-server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - game

  postgres:
    image: postgres:14
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h 127.0.0.1 -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - game

networks:
  game:
    driver: bridge
