ARG NODE_VERSION=20
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-bookworm AS base

WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/shared/dist/ /app/packages/server/dist/ && yarn build:server


FROM node:$NODE_VERSION-bookworm-slim AS production
WORKDIR /app

COPY --from=builder /app/package.json /app/yarn.lock /app/lerna.json ./
COPY --from=builder /app/packages/server/package.json /app/packages/server/package.json
COPY --from=builder /app/packages/shared/package.json /app/packages/shared/package.json
RUN yarn install --production=true --frozen-lockfile --ignore-scripts
COPY --from=builder /app/packages/server/dist/ /app/packages/server/dist/
COPY --from=builder /app/packages/shared/dist/ /app/packages/shared/dist/

EXPOSE $SERVER_PORT
CMD [ "node", "/app/packages/server/dist/index.js" ]
