ARG NODE_VERSION=20
ARG CLIENT_PORT=3000

FROM node:$NODE_VERSION-bookworm AS base

WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/shared/dist/ /app/packages/client/dist/ && yarn build:client

FROM node:$NODE_VERSION-bookworm-slim AS production
WORKDIR /app

COPY --from=builder /app/package.json /app/yarn.lock /app/lerna.json ./
COPY --from=builder /app/packages/client/package.json /app/packages/client/package.json
COPY --from=builder /app/packages/shared/package.json /app/packages/shared/package.json
RUN yarn install --production=true --frozen-lockfile --ignore-scripts
COPY --from=builder /app/packages/client/dist/ /app/packages/client/dist/
COPY --from=builder /app/packages/client/server/ /app/packages/client/server/
COPY --from=builder /app/packages/shared/dist/ /app/packages/shared/dist/

EXPOSE $CLIENT_PORT
CMD [ "node", "/app/packages/client/server/index.js" ]
